In [2]:
import pandas as pd

# Phase One

In [3]:
data = pd.read_csv('./data/online_retail_practice_sample.csv')
df = pd.DataFrame(data)
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,15-09-2011 15:26,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,05-06-2011 08:10,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,24-07-2011 03:45,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,04-09-2011 16:55,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,23-02-2011 13:40,3.39,16830.0,Sweden
...,...,...,...,...,...,...,...,...
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,20-09-2011 00:21,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,13-11-2011 09:05,12.75,13615.0,EIRE
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,07-04-2011 12:48,5.10,16943.0,Spain
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,24-09-2011 16:24,2.55,17478.0,Portugal
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,24-08-2011 00:48,2.55,17296.0,Germany

In [4]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,15-09-2011 15:26,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,05-06-2011 08:10,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,24-07-2011 03:45,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,04-09-2011 16:55,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,23-02-2011 13:40,3.39,16830.0,Sweden

In [5]:
df.tail(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1602,576798,22633,HAND WARMER UNION JACK,8,20-03-2011 15:46,2.10,16068.0,Australia
1603,549401,21730,GLASS STAR FROSTED T-LIGHT HOLDER,5,25-05-2011 22:09,3.40,13436.0,Portugal
1604,565607,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,1,24-07-2011 17:52,2.71,13346.0,Netherlands
1605,569476,22423,REGENCY CAKESTAND 3 TIER,4,19-04-2011 21:53,12.75,17314.0,Sweden
1606,C554322,21212,PACK OF 72 RETROSPOT CAKE CASES,-6,16-08-2011 02:22,0.55,18187.0,Sweden
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,20-09-2011 00:21,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,13-11-2011 09:05,12.75,13615.0,EIRE
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,07-04-2011 12:48,5.10,16943.0,Spain
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,24-09-2011 16:24,2.55,17478.0,Portugal
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,24-08-2011 00:48,2.55,17296.0,Germany

In [6]:
df.sample(15, random_state = 42)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
29,565045,22752,SET 7 BABUSHKA NESTING BOXES,8,05-10-2011 07:59,7.65,17321.0,Netherlands
259,544497,POST,POSTAGE,2,10-12-2010 14:46,21.60,15411.0,France
383,539123,71053,WHITE METAL LANTERN,12,09-02-2011 04:06,4.07,14097.0,France
425,565669,79323P,PINK CHERRY LIGHTS,14,13-07-2011 11:38,5.40,14394.0,EIRE
239,559785,71053,WHITE METAL LANTERN,8,20-08-2011 18:01,4.07,17429.0,Sweden
787,562769,21977,PACK OF 60 PINK PAISLEY CAKE CASES,11,16-03-2011 12:30,0.66,12969.0,Australia
1471,544897,21977,PACK OF 60 PINK PAISLEY CAKE CASES,8,18-07-2011 18:26,0.55,18175.0,Portugal
497,561669,21730,GLASS STAR FROSTED T-LIGHT HOLDER,8,01-02-2011 01:20,4.25,14894.0,Spain
495,566207,21212,PACK OF 72 RETROSPOT CAKE CASES,11,29-08-2011 00:28,0.55,14557.0,France
754,568872,84406B,CREAM CUPID HEARTS COAT HANGER,12,12-09-2011 09:05,3.30,14377.0,United Kingdom
411,572532,21977,PACK OF 60 PINK PAISLEY CAKE CASES,1,20-07-2011 17:18,0.55,16634.0,Germany
1581,552090,21730,GLASS STAR FROSTED T-LIGHT HOLDER,9,19-01-2011 21:03,5.10,13181.0,France
720,C537033,22752,SET 7 BABUSHKA NESTING BOXES,-5,03-08-2011 23:56,7.65,16639.0,United Kingdom
247,576014,85123A,WHITE HANGING HEART T-LIGHT HOLDER,5,11-06-2011 17:56,2.04,12691.0,United Kingdom
567,547774,79323P,PINK CHERRY LIGHTS,13,24-01-2011 11:59,5.40,14055.0,Netherlands

In [7]:
df.shape

(1612, 8)

In [8]:
df.columns.tolist()

['InvoiceNo',
 'StockCode',
 'Description',
 'Quantity',
 'InvoiceDate',
 'UnitPrice',
 'CustomerID',
 'Country']

In [9]:
df.dtypes

InvoiceNo          str
StockCode          str
Description        str
Quantity         int64
InvoiceDate        str
UnitPrice      float64
CustomerID     float64
Country            str
dtype: object

In [10]:
df.head(20)['Description']

0                     WHITE METAL LANTERN
1       GLASS STAR FROSTED T-LIGHT HOLDER
2     KNITTED UNION FLAG HOT WATER BOTTLE
3                     WHITE METAL LANTERN
4     KNITTED UNION FLAG HOT WATER BOTTLE
5     KNITTED UNION FLAG HOT WATER BOTTLE
6                                 POSTAGE
7                                 POSTAGE
8      PACK OF 60 PINK PAISLEY CAKE CASES
9                     WHITE METAL LANTERN
10                 HAND WARMER UNION JACK
11        PACK OF 72 RETROSPOT CAKE CASES
12                                POSTAGE
13           SET 7 BABUSHKA NESTING BOXES
14      GLASS STAR FROSTED T-LIGHT HOLDER
15     PACK OF 60 PINK PAISLEY CAKE CASES
16                                POSTAGE
17               REGENCY CAKESTAND 3 TIER
18                     PINK CHERRY LIGHTS
19               REGENCY CAKESTAND 3 TIER
Name: Description, dtype: str

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1612 entries, 0 to 1611
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    1612 non-null   str
 1   StockCode    1612 non-null   str
 2   Description  1589 non-null   str
 3   Quantity     1612 non-null   int64
 4   InvoiceDate  1612 non-null   str
 5   UnitPrice    1612 non-null   float64
 6   CustomerID   1541 non-null   float64
 7   Country      1599 non-null   str
dtypes: float64(2), int64(1), str(5)
memory usage: 100.9 KB

# Phase Two

In [12]:
new_data = df.drop(columns='InvoiceDate')
new_data
new_data.to_csv("./output/online_retail.csv", index=False)

In [13]:
data = pd.read_csv('./output/online_retail.csv')
df = pd.DataFrame(data)
df

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,3.39,16830.0,Sweden
...,...,...,...,...,...,...,...
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,12.75,13615.0,EIRE
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,5.10,16943.0,Spain
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2.55,17478.0,Portugal
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,17296.0,Germany

In [14]:
smdf = df.head(10)
smdf

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,3.39,16830.0,Sweden
5,561166,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,3,4.07,12343.0,Spain
6,570510,POST,POSTAGE,4,14.40,12767.0,United Kingdom
7,574557,POST,POSTAGE,1,21.60,13566.0,France
8,572698,21977,PACK OF 60 PINK PAISLEY CAKE CASES,2,0.55,14765.0,Germany
9,547022,71053,WHITE METAL LANTERN,7,4.07,15256.0,EIRE

In [15]:
df[['Quantity', 'UnitPrice']].describe()

          Quantity    UnitPrice
count  1612.000000  1612.000000
mean      7.158189     5.523189
std       5.890089     5.191564
min     -15.000000     0.000000
25%       4.000000     2.200000
50%       8.000000     3.390000
75%      12.000000     7.650000
max      15.000000    21.600000

In [16]:
df[['Country', 'Description']].describe()

       Country Description
count     1599        1589
unique      10          22
top     France     POSTAGE
freq       178         143

In [17]:
df.describe()

          Quantity    UnitPrice    CustomerID
count  1612.000000  1612.000000   1541.000000
mean      7.158189     5.523189  15201.415315
std       5.890089     5.191564   1693.230069
min     -15.000000     0.000000  12305.000000
25%       4.000000     2.200000  13708.000000
50%       8.000000     3.390000  15220.000000
75%      12.000000     7.650000  16640.000000
max      15.000000    21.600000  18196.000000

In [18]:
df.isnull().sum()

InvoiceNo       0
StockCode       0
Description    23
Quantity        0
UnitPrice       0
CustomerID     71
Country        13
dtype: int64

In [19]:
unique_df = df.drop_duplicates()
unique_df

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,3.39,16830.0,Sweden
...,...,...,...,...,...,...,...
1595,564607,POST,POSTAGE,15,18.00,13500.0,Netherlands
1596,576989,85123A,WHITE HANGING HEART T-LIGHT HOLDER,10,3.06,13704.0,Australia
1597,C555041,79323P,PINK CHERRY LIGHTS,-14,6.75,14111.0,France
1598,567397,71053,WHITE METAL LANTERN,8,3.39,17260.0,United Kingdom
1599,570077,21730,GLASS STAR FROSTED T-LIGHT HOLDER,10,4.25,12345.0,Belgium

In [20]:
unique_df['Country'].value_counts()

Country
France            178
Belgium           164
Spain             163
Australia         163
Sweden            160
United Kingdom    159
Netherlands       157
EIRE              154
Portugal          145
Germany           144
Name: count, dtype: int64

In [21]:
unique_df['Country'].unique()

<StringArray>
[        'Sweden',    'Netherlands',          'Spain', 'United Kingdom',
         'France',        'Germany',           'EIRE',       'Portugal',
        'Belgium',      'Australia',              nan]
Length: 11, dtype: str

In [22]:
df['Country'].value_counts().head(10)

Country
France            178
Spain             165
Australia         165
Belgium           164
Sweden            162
United Kingdom    160
Netherlands       158
EIRE              155
Portugal          147
Germany           145
Name: count, dtype: int64

In [23]:
summary = pd.DataFrame({
    'Metric': ['Rows', 'Columns', 'Unique Products', 'Unique Invoices'],
    'Value': [
        len(df),
        df.shape[1],
        df['Description'].nunique(),
        df['InvoiceNo'].nunique()
    ]
})
summary.to_csv('./output/summary.csv', index=False)

# Phase Three

In [24]:
data = pd.read_csv('./data/online_retail_practice_sample.csv')
df = pd.DataFrame(data)
df[['InvoiceNo', 'InvoiceDate']]

     InvoiceNo       InvoiceDate
0       570338  15-09-2011 15:26
1       574674  05-06-2011 08:10
2       545052  24-07-2011 03:45
3       567005  04-09-2011 16:55
4       573512  23-02-2011 13:40
...        ...               ...
1607    546730  20-09-2011 00:21
1608    556479  13-11-2011 09:05
1609   C541876  07-04-2011 12:48
1610    553299  24-09-2011 16:24
1611    537515  24-08-2011 00:48

[1612 rows x 2 columns]

In [25]:
print(df.iloc[4])
df.loc[4]

InvoiceNo                                   573512
StockCode                                   84029G
Description    KNITTED UNION FLAG HOT WATER BOTTLE
Quantity                                        15
InvoiceDate                       23-02-2011 13:40
UnitPrice                                     3.39
CustomerID                                 16830.0
Country                                     Sweden
Name: 4, dtype: object

InvoiceNo                                   573512
StockCode                                   84029G
Description    KNITTED UNION FLAG HOT WATER BOTTLE
Quantity                                        15
InvoiceDate                       23-02-2011 13:40
UnitPrice                                     3.39
CustomerID                                 16830.0
Country                                     Sweden
Name: 4, dtype: object

- Row Position (iloc): Refers to the physical location of the row in the DataFrame, starting from 0.  This is a fixed positional index; iloc[0] always returns the first row, even if the DataFrame is sorted or filtered.

- Index Label (loc): Refers to the identifier assigned to the row (e.g., a timestamp, ID, or custom string). This label is logical and can change positions if the data is reordered; loc['A'] returns the row with the label 'A', regardless of where it sits in the table.

In [27]:
result = df.loc[100:110, ["Description", "UnitPrice"]]
result

                           Description  UnitPrice
100                            POSTAGE      18.00
101                            POSTAGE      21.60
102                WHITE METAL LANTERN       3.39
103  GLASS STAR FROSTED T-LIGHT HOLDER       5.10
104             HAND WARMER UNION JACK       2.10
105  GLASS STAR FROSTED T-LIGHT HOLDER       4.25
106  GLASS STAR FROSTED T-LIGHT HOLDER       4.25
107       SET 7 BABUSHKA NESTING BOXES       7.65
108    PACK OF 72 RETROSPOT CAKE CASES       0.66
109           REGENCY CAKESTAND 3 TIER      12.75
110             HAND WARMER UNION JACK       2.10

In [28]:
data[data['Quantity']>10]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,05-06-2011 08:10,4.25,17154.0,Sweden
3,567005,71053,WHITE METAL LANTERN,12,04-09-2011 16:55,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,23-02-2011 13:40,3.39,16830.0,Sweden
10,567596,22633,HAND WARMER UNION JACK,15,24-07-2011 14:21,1.68,15220.0,France
18,580659,79323P,PINK CHERRY LIGHTS,15,11-06-2011 21:15,8.10,18019.0,Sweden
...,...,...,...,...,...,...,...,...
1593,560762,21730,GLASS STAR FROSTED T-LIGHT HOLDER,11,22-07-2011 02:33,4.25,15530.0,Belgium
1595,564607,POST,POSTAGE,15,02-07-2011 04:57,18.00,13500.0,Netherlands
1601,540834,POST,POSTAGE,14,26-01-2011 11:06,21.60,13594.0,United Kingdom
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,20-09-2011 00:21,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,13-11-2011 09:05,12.75,13615.0,EIRE

In [31]:
data[data['UnitPrice']>50]

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

In [32]:
data[data['Country']=='France']

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
7,574557,POST,POSTAGE,1,23-09-2011 07:36,21.60,13566.0,France
10,567596,22633,HAND WARMER UNION JACK,15,24-07-2011 14:21,1.68,15220.0,France
17,564700,22423,REGENCY CAKESTAND 3 TIER,1,29-11-2011 05:14,12.75,14488.0,France
19,553325,22423,REGENCY CAKESTAND 3 TIER,8,22-02-2011 21:06,10.20,16854.0,France
20,563118,85123A,WHITE HANGING HEART T-LIGHT HOLDER,1,15-11-2011 22:14,2.04,14466.0,France
...,...,...,...,...,...,...,...,...
1568,C571045,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,-1,07-12-2011 12:08,3.39,14746.0,France
1580,536758,22633,HAND WARMER UNION JACK,5,10-01-2011 10:03,1.68,14476.0,France
1581,552090,21730,GLASS STAR FROSTED T-LIGHT HOLDER,9,19-01-2011 21:03,5.10,13181.0,France
1591,560681,71053,WHITE METAL LANTERN,15,26-09-2011 08:49,4.07,16346.0,France
1597,C555041,79323P,PINK CHERRY LIGHTS,-14,06-11-2011 12:02,6.75,14111.0,France

In [33]:
top_5_countries=data['Country'].value_counts().head(5).index
data[data['Country'].isin(top_5_countries)]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,15-09-2011 15:26,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,05-06-2011 08:10,4.25,17154.0,Sweden
3,567005,71053,WHITE METAL LANTERN,12,04-09-2011 16:55,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,23-02-2011 13:40,3.39,16830.0,Sweden
5,561166,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,3,28-02-2011 16:38,4.07,12343.0,Spain
...,...,...,...,...,...,...,...,...
1602,576798,22633,HAND WARMER UNION JACK,8,20-03-2011 15:46,2.10,16068.0,Australia
1605,569476,22423,REGENCY CAKESTAND 3 TIER,4,19-04-2011 21:53,12.75,17314.0,Sweden
1606,C554322,21212,PACK OF 72 RETROSPOT CAKE CASES,-6,16-08-2011 02:22,0.55,18187.0,Sweden
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,20-09-2011 00:21,4.25,16326.0,Spain
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,07-04-2011 12:48,5.10,16943.0,Spain

In [34]:
data[data['Quantity'].between(5,20)]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,15-09-2011 15:26,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,05-06-2011 08:10,4.25,17154.0,Sweden
3,567005,71053,WHITE METAL LANTERN,12,04-09-2011 16:55,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,23-02-2011 13:40,3.39,16830.0,Sweden
9,547022,71053,WHITE METAL LANTERN,7,14-09-2011 17:41,4.07,15256.0,EIRE
...,...,...,...,...,...,...,...,...
1603,549401,21730,GLASS STAR FROSTED T-LIGHT HOLDER,5,25-05-2011 22:09,3.40,13436.0,Portugal
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,20-09-2011 00:21,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,13-11-2011 09:05,12.75,13615.0,EIRE
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,24-09-2011 16:24,2.55,17478.0,Portugal
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,24-08-2011 00:48,2.55,17296.0,Germany

In [35]:
data.query("Quantity>10 and UnitPrice>5")

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
18,580659,79323P,PINK CHERRY LIGHTS,15,11-06-2011 21:15,8.10,18019.0,Sweden
31,550785,22423,REGENCY CAKESTAND 3 TIER,15,25-09-2011 21:14,12.75,16898.0,Netherlands
38,566325,22423,REGENCY CAKESTAND 3 TIER,11,14-01-2011 18:07,10.20,13528.0,Sweden
69,566686,22423,REGENCY CAKESTAND 3 TIER,13,14-06-2011 08:46,12.75,15782.0,United Kingdom
89,577425,22752,SET 7 BABUSHKA NESTING BOXES,14,16-11-2011 02:46,6.12,16327.0,Sweden
...,...,...,...,...,...,...,...,...
1575,547919,22423,REGENCY CAKESTAND 3 TIER,11,09-04-2011 18:38,12.75,16277.0,EIRE
1587,572765,21730,GLASS STAR FROSTED T-LIGHT HOLDER,15,12-12-2010 17:20,5.10,17421.0,Belgium
1595,564607,POST,POSTAGE,15,02-07-2011 04:57,18.00,13500.0,Netherlands
1601,540834,POST,POSTAGE,14,26-01-2011 11:06,21.60,13594.0,United Kingdom
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,13-11-2011 09:05,12.75,13615.0,EIRE

In [36]:
data.sort_values(by='UnitPrice',ascending=False).head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1248,565100,POST,POSTAGE,14,25-11-2011 20:27,21.6,13873.0,Australia
1253,573477,POST,POSTAGE,8,22-04-2011 14:47,21.6,18172.0,EIRE
49,557529,POST,POSTAGE,7,19-08-2011 06:38,21.6,17690.0,Australia
465,569506,POST,POSTAGE,6,08-11-2011 11:22,21.6,16513.0,Australia
932,C561717,POST,POSTAGE,-11,22-11-2011 12:10,21.6,15675.0,Netherlands
1528,565108,POST,POSTAGE,10,29-03-2011 08:51,21.6,16176.0,France
1560,567925,POST,POSTAGE,4,20-01-2011 13:21,21.6,17041.0,France
101,573603,POST,POSTAGE,8,16-03-2011 11:27,21.6,14863.0,Australia
764,572968,POST,POSTAGE,6,22-07-2011 19:28,21.6,16251.0,Germany
502,C543573,POST,POSTAGE,-15,26-05-2011 09:37,21.6,17799.0,Spain
833,574836,POST,POSTAGE,2,21-05-2011 21:25,21.6,14562.0,EIRE
501,552616,POST,POSTAGE,6,15-05-2011 13:37,21.6,12473.0,France
752,549960,POST,POSTAGE,15,20-10-2011 05:17,21.6,14865.0,Australia
353,570905,POST,POSTAGE,12,18-05-2011 16:49,21.6,NaN,United Kingdom
359,547600,POST,POSTAGE,8,08-10-2011 10:31,21.6,14477.0,Portugal
456,578392,POST,POSTAGE,1,16-12-2010 14:40,21.6,15550.0,Germany
1601,540834,POST,POSTAGE,14,26-01-2011 11:06,21.6,13594.0,United Kingdom
7,574557,POST,POSTAGE,1,23-09-2011 07:36,21.6,13566.0,France
617,540834,POST,POSTAGE,14,26-01-2011 11:06,21.6,13594.0,United Kingdom
893,565522,POST,POSTAGE,1,02-08-2011 16:33,21.6,13623.0,United Kingdom

# Phase Four

In [37]:
df_raw = data.copy()
data = df_raw.copy()
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,15-09-2011 15:26,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,05-06-2011 08:10,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,24-07-2011 03:45,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,04-09-2011 16:55,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,23-02-2011 13:40,3.39,16830.0,Sweden
...,...,...,...,...,...,...,...,...
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,20-09-2011 00:21,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,13-11-2011 09:05,12.75,13615.0,EIRE
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,07-04-2011 12:48,5.10,16943.0,Spain
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,24-09-2011 16:24,2.55,17478.0,Portugal
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,24-08-2011 00:48,2.55,17296.0,Germany

In [38]:
data = df_raw.copy()
data = data.rename(columns={'Description':'productDescription'})
data.head()

,InvoiceNo,StockCode,productDescription,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,15-09-2011 15:26,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,05-06-2011 08:10,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,24-07-2011 03:45,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,04-09-2011 16:55,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,23-02-2011 13:40,3.39,16830.0,Sweden

In [39]:
data['Revenue'] = data['Quantity']*data['UnitPrice']
data.head()

,InvoiceNo,StockCode,productDescription,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,570338,71053,WHITE METAL LANTERN,7,15-09-2011 15:26,4.07,16640.0,Sweden,28.49
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,05-06-2011 08:10,4.25,17154.0,Sweden,59.50
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,24-07-2011 03:45,3.39,16783.0,Netherlands,0.00
3,567005,71053,WHITE METAL LANTERN,12,04-09-2011 16:55,3.39,14222.0,Spain,40.68
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,23-02-2011 13:40,3.39,16830.0,Sweden,50.85

In [41]:
import numpy as np
data['TransactionType'] = np.select(
    [
        data['InvoiceNo'].astype(str).str.startswith('C'),
        data['Quantity'] < 0,
        data['Quantity'] > 0
    ],
    [
        'Cancellation',
        'Return',
        'Positive Sale'
    ],
    default='Other/Invalid'
)
data['TransactionType'].value_counts()

TransactionType
Positive Sale    1498
Cancellation      105
Other/Invalid       9
Name: count, dtype: int64

In [42]:
data['IsIdentifiedCustomer'] = data['CustomerID'].notna()
data.head()

,InvoiceNo,StockCode,productDescription,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,TransactionType,IsIdentifiedCustomer
0,570338,71053,WHITE METAL LANTERN,7,15-09-2011 15:26,4.07,16640.0,Sweden,28.49,Positive Sale,True
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,05-06-2011 08:10,4.25,17154.0,Sweden,59.50,Positive Sale,True
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,24-07-2011 03:45,3.39,16783.0,Netherlands,0.00,Other/Invalid,True
3,567005,71053,WHITE METAL LANTERN,12,04-09-2011 16:55,3.39,14222.0,Spain,40.68,Positive Sale,True
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,23-02-2011 13:40,3.39,16830.0,Sweden,50.85,Positive Sale,True

In [44]:
data['InvoiceDate'] = pd.to_datetime(data['InvoiceDate'])
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1612 entries, 0 to 1611
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   InvoiceNo             1612 non-null   str
 1   StockCode             1612 non-null   str
 2   productDescription    1589 non-null   str
 3   Quantity              1612 non-null   int64
 4   InvoiceDate           1612 non-null   datetime64[us]
 5   UnitPrice             1612 non-null   float64
 6   CustomerID            1541 non-null   float64
 7   Country               1599 non-null   str
 8   Revenue               1612 non-null   float64
 9   TransactionType       1612 non-null   str
 10  IsIdentifiedCustomer  1612 non-null   bool
dtypes: bool(1), datetime64[us](1), float64(3), int64(1), str(5)
memory usage: 127.6 KB

In [45]:
data['InvoiceNo'] = data['InvoiceNo'].astype('string')
data['StockCode'] = data['StockCode'].astype('string')
data['Country'] = data['Country'].astype('string')
data.dtypes

InvoiceNo                       string
StockCode                       string
productDescription                 str
Quantity                         int64
InvoiceDate             datetime64[us]
UnitPrice                      float64
CustomerID                     float64
Country                         string
Revenue                        float64
TransactionType                    str
IsIdentifiedCustomer              bool
dtype: object

In [46]:
cols = [
    'InvoiceNo', 'InvoiceDate', 'StockCode', 'ProductDescription',
    'CustomerID', 'Country', 'Quantity', 'UnitPrice', 'Revenue',
    'TransactionType', 'IsIdentifiedCustomer'
]
data = data[[col for col in cols if col in data.columns]]
data.head()

,InvoiceNo,InvoiceDate,StockCode,CustomerID,Country,Quantity,UnitPrice,Revenue,TransactionType,IsIdentifiedCustomer
0,570338,2011-09-15 15:26:00,71053,16640.0,Sweden,7,4.07,28.49,Positive Sale,True
1,574674,2011-06-05 08:10:00,21730,17154.0,Sweden,14,4.25,59.50,Positive Sale,True
2,545052,2011-07-24 03:45:00,84029G,16783.0,Netherlands,0,3.39,0.00,Other/Invalid,True
3,567005,2011-09-04 16:55:00,71053,14222.0,Spain,12,3.39,40.68,Positive Sale,True
4,573512,2011-02-23 13:40:00,84029G,16830.0,Sweden,15,3.39,50.85,Positive Sale,True

In [47]:
data = data.sort_values(by=['InvoiceDate', 'InvoiceNo'])
data.head()

,InvoiceNo,InvoiceDate,StockCode,CustomerID,Country,Quantity,UnitPrice,Revenue,TransactionType,IsIdentifiedCustomer
1523,569444,2010-12-01 00:05:00,71053,13845.0,Germany,15,3.39,50.85,Positive Sale,True
122,C543863,2010-12-01 02:26:00,84406B,14319.0,France,-13,2.75,-35.75,Cancellation,True
409,568184,2010-12-01 03:57:00,84406B,15058.0,France,3,2.20,6.60,Positive Sale,True
78,C551232,2010-12-01 06:06:00,71053,12472.0,Spain,-7,4.07,-28.49,Cancellation,True
1312,536850,2010-12-01 21:38:00,22423,12972.0,Sweden,9,10.20,91.80,Positive Sale,True

In [48]:
data = data.reset_index(drop=True)
print(data.index)
print(data.index.is_unique)
print(data.index.equals(pd.RangeIndex(start=0, stop=len(data))))

RangeIndex(start=0, stop=1612, step=1)
True
True

# Phase Five

In [50]:
missing_count = data.isnull().sum()
missing_percentage = (missing_count / len(data)) * 100

missing_report = pd.DataFrame({
    'MissingCount': missing_count,
    'MissingPercentage': missing_percentage
})
missing_report

                      MissingCount  MissingPercentage
InvoiceNo                        0           0.000000
InvoiceDate                      0           0.000000
StockCode                        0           0.000000
CustomerID                      71           4.404467
Country                         13           0.806452
Quantity                         0           0.000000
UnitPrice                        0           0.000000
Revenue                          0           0.000000
TransactionType                  0           0.000000
IsIdentifiedCustomer             0           0.000000

In [51]:
missing_report.sort_values(
    by='MissingPercentage',
    ascending=False
)

                      MissingCount  MissingPercentage
CustomerID                      71           4.404467
Country                         13           0.806452
InvoiceDate                      0           0.000000
InvoiceNo                        0           0.000000
StockCode                        0           0.000000
Quantity                         0           0.000000
UnitPrice                        0           0.000000
Revenue                          0           0.000000
TransactionType                  0           0.000000
IsIdentifiedCustomer             0           0.000000

In [52]:
data[data['CustomerID'].isna()]

,InvoiceNo,InvoiceDate,StockCode,CustomerID,Country,Quantity,UnitPrice,Revenue,TransactionType,IsIdentifiedCustomer
14,549594,2010-12-03 13:48:00,POST,NaN,Belgium,13,18.00,234.00,Positive Sale,False
101,C569164,2010-12-22 13:25:00,71053,NaN,Germany,-5,4.07,-20.35,Cancellation,False
125,550375,2010-12-29 06:33:00,85123A,NaN,Spain,6,2.55,15.30,Positive Sale,False
146,561467,2011-01-05 07:47:00,POST,NaN,Australia,14,18.00,252.00,Positive Sale,False
154,573565,2011-01-08 03:20:00,84406B,NaN,Netherlands,12,2.20,26.40,Positive Sale,False
...,...,...,...,...,...,...,...,...,...,...
1516,540081,2011-11-18 20:23:00,79323P,NaN,United Kingdom,2,0.00,0.00,Positive Sale,False
1549,560412,2011-11-24 12:27:00,21977,NaN,Portugal,9,0.44,3.96,Positive Sale,False
1558,542958,2011-11-26 20:13:00,79323P,NaN,Netherlands,11,6.75,74.25,Positive Sale,False
1575,568423,2011-12-01 13:25:00,22423,NaN,EIRE,11,10.20,112.20,Positive Sale,False
1582,550723,2011-12-02 18:44:00,79323P,NaN,Belgium,15,6.75,101.25,Positive Sale,False

In [53]:
missing_report = pd.DataFrame({
    'ColumnName': data.columns,
    'MissingCount': data.isnull().sum().values,
    'NonMissingCount': data.notnull().sum().values,
    'MissingPercentage': (data.isnull().mean() * 100).values
})
missing_report

             ColumnName  MissingCount  NonMissingCount  MissingPercentage
0             InvoiceNo             0             1612           0.000000
1           InvoiceDate             0             1612           0.000000
2             StockCode             0             1612           0.000000
3            CustomerID            71             1541           4.404467
4               Country            13             1599           0.806452
5              Quantity             0             1612           0.000000
6             UnitPrice             0             1612           0.000000
7               Revenue             0             1612           0.000000
8       TransactionType             0             1612           0.000000
9  IsIdentifiedCustomer             0             1612           0.000000

In [54]:
data.duplicated().sum()

np.int64(12)

In [55]:
data_clean = data.drop_duplicates().copy()
print("Records before cleaning:", len(data))
print("Records after cleaning:", len(data_clean))

Records before cleaning: 1612
Records after cleaning: 1600

In [56]:
data.groupby(['InvoiceNo', 'StockCode']).size().reset_index(name='Count').query('Count > 1')

     InvoiceNo StockCode  Count
46      537515    85123A      2
164     540834      POST      2
337     546048    85123A      2
359     546730     21730      2
454     549401     21730      2
593     553299    85123A      2
706     556479     22423      2
981     565607    84029G      2
1100    569476     22423      2
1274    574232     71053      2
1373    576798     22633      2
1504   C541876     21730      2
1547   C554322     21212      2

In [57]:
print(data_clean['CustomerID'].isna().sum())

71

In [58]:
data_quality_report = pd.DataFrame({
    'Metric': [
        'Row Count',
        'Missing Values',
        'Exact Duplicate Rows'
    ],
    'Before Cleaning': [
        len(data),
        data.isna().sum().sum(),
        data.duplicated().sum()
    ],
    'After Cleaning': [
        len(data_clean),
        data_clean.isna().sum().sum(),
        data_clean.duplicated().sum()
    ]
})
data_quality_report

                 Metric  Before Cleaning  After Cleaning
0             Row Count             1612            1600
1        Missing Values               84              84
2  Exact Duplicate Rows               12               0

In [59]:
data_quality_report.to_csv("data_quality_report.csv",index=False)
print("Data quality report saved succcessfully!")

Data quality report saved succcessfully!